server:
  port: 8090
  
spring:
  datasource:
    username: sa
    password: 
    url: jdbc:h2:~/test  #jdbc:h2:~/test #jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 300
      idle-timeout: 600
      max-lifetime: 1800
      pool-name: StudentConnectionPool
  jpa:
    hibernate:  
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.H2Dialect       
    
    
    
    
    
    
    
    
